apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventing-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eventing-api
  template:
    metadata:
      labels:
        app: eventing-api
      annotations:
        init-job-hash: "${DB_INIT_JOB_HASH}"  # This will force pod restart when init job changes
    spec:
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ['sh', '-c', 'until nc -z postgres-service 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: eventing-api
        image: eventing-api:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "development"
        - name: DB_HOST
          value: "postgres-service"
        - name: DB_PORT
          value: "5432"
        - name: DB_NAME
          value: "eventing"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "postgres_password"
